In [1]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
df = pd.read_csv('house-prices-advanced-regression-techniques/X_train.csv')

In [3]:
df

,Id,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,12.247694,0.235294,0.75,0.418208,0.366344,1.0,1.0,0.000000,0.333333,...,1.00,1.0,0.00000,0.090909,0.50,0.666667,0.75,0.0,0.0,0.0
1,2,12.109011,0.000000,0.75,0.495064,0.391317,1.0,1.0,0.000000,0.333333,...,1.00,1.0,0.00000,0.363636,0.25,0.666667,0.75,0.0,0.0,0.0
2,3,12.317167,0.235294,0.75,0.434909,0.422359,1.0,1.0,0.333333,0.333333,...,1.00,1.0,0.00000,0.727273,0.50,0.666667,0.75,0.0,0.0,0.0
3,4,11.849398,0.294118,0.75,0.388581,0.390295,1.0,1.0,0.333333,0.333333,...,1.00,1.0,0.00000,0.090909,0.00,0.666667,0.00,0.0,0.0,0.0
4,5,12.429216,0.235294,0.75,0.513123,0.468761,1.0,1.0,0.333333,0.333333,...,1.00,1.0,0.00000,1.000000,0.50,0.666667,0.75,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,12.072541,0.235294,0.75,0.400718,0.353592,1.0,1.0,0.000000,0.333333,...,1.00,1.0,0.00000,0.636364,0.25,0.666667,0.75,0.0,0.0,0.0
1456,1457,12.254863,0.000000,0.75,0.517503,0.453273,1.0,1.0,0.000000,0.333333,...,0.50,1.0,0.00000,0.090909,1.00,0.666667,0.75,0.0,0.0,0.0
1457,1458,12.493130,0.294118,0.75,0.423859,0.379597,1.0,1.0,0.000000,0.333333,...,0.75,0.5,0.16129,0.363636,1.00,0.666667,0.75,0.0,0.0,0.0
1458,1459,11.864462,0.000000,0.75,0.434909,0.393688,1.0,1.0,0.000000,0.333333,...,1.00,1.0,0.00000,0.272727,1.00,0.666667,0.75,0.0,0.0,0.0
1459,1460,11.901583,0.000000,0.75,0.471175,0.398069,1.0,1.0,0.000000,0.333333,...,1.00,1.0,0.00000,0.454545,0.50,0.666667,0.75,0.0,0.0,0.0

In [4]:
y = df['SalePrice']
y

0       12.247694
1       12.109011
2       12.317167
3       11.849398
4       12.429216
          ...
1455    12.072541
1456    12.254863
1457    12.493130
1458    11.864462
1459    11.901583
Name: SalePrice, Length: 1460, dtype: float64

In [5]:
X = df.drop(columns='SalePrice')
X.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,0.235294,0.75,0.418208,0.366344,1.0,1.0,0.000000,0.333333,1.0,...,1.0,1.0,0.000000,0.090909,0.50,0.666667,0.75,0.0,0.0,0.0
1,2,0.000000,0.75,0.495064,0.391317,1.0,1.0,0.000000,0.333333,1.0,...,1.0,1.0,0.000000,0.363636,0.25,0.666667,0.75,0.0,0.0,0.0
2,3,0.235294,0.75,0.434909,0.422359,1.0,1.0,0.333333,0.333333,1.0,...,1.0,1.0,0.000000,0.727273,0.50,0.666667,0.75,0.0,0.0,0.0
3,4,0.294118,0.75,0.388581,0.390295,1.0,1.0,0.333333,0.333333,1.0,...,1.0,1.0,0.000000,0.090909,0.00,0.666667,0.00,0.0,0.0,0.0
4,5,0.235294,0.75,0.513123,0.468761,1.0,1.0,0.333333,0.333333,1.0,...,1.0,1.0,0.000000,1.000000,0.50,0.666667,0.75,0.0,0.0,0.0
5,6,0.176471,0.75,0.517503,0.466761,1.0,1.0,0.333333,0.333333,1.0,...,0.5,0.5,0.045161,0.818182,0.75,0.666667,0.75,0.0,0.0,0.0
6,7,0.000000,0.75,0.471175,0.400943,1.0,1.0,0.000000,0.333333,1.0,...,1.0,1.0,0.000000,0.636364,0.25,0.666667,0.75,0.0,0.0,0.0
7,8,0.235294,0.75,0.440313,0.406643,1.0,1.0,0.333333,0.333333,1.0,...,1.0,0.5,0.022581,0.909091,0.75,0.666667,0.75,1.0,0.0,0.0
8,9,0.176471,0.25,0.328426,0.303205,1.0,1.0,0.000000,0.333333,1.0,...,1.0,1.0,0.000000,0.272727,0.50,0.666667,0.00,0.0,0.0,0.0
9,10,1.000000,0.75,0.321097,0.340903,1.0,1.0,0.000000,0.333333,1.0,...,1.0,1.0,0.000000,0.000000,0.50,0.666667,0.75,0.0,0.0,0.0

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [7]:
X_train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
254,255,0.000000,0.75,0.445638,0.365182,1.0,1.0,0.000000,0.333333,1.0,...,1.00,1.0,0.0,0.454545,1.00,0.666667,0.75,0.0,0.0,0.0
1066,1067,0.235294,0.75,0.382360,0.351604,1.0,1.0,0.333333,0.333333,1.0,...,1.00,1.0,0.0,0.363636,0.75,0.666667,0.75,0.0,0.0,0.0
638,639,0.058824,0.75,0.429425,0.373775,1.0,1.0,0.000000,0.333333,1.0,...,0.50,1.0,0.0,0.363636,0.50,0.666667,0.75,0.0,0.0,1.0
799,800,0.176471,0.75,0.388581,0.335012,1.0,1.0,0.000000,0.333333,1.0,...,0.50,1.0,0.0,0.454545,0.25,0.666667,0.75,0.0,0.0,0.0
380,381,0.176471,0.75,0.321097,0.263645,1.0,0.5,0.000000,0.333333,1.0,...,1.00,1.0,0.0,0.363636,1.00,0.666667,0.75,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1095,1096,0.000000,0.75,0.485693,0.385460,1.0,1.0,0.333333,0.333333,1.0,...,1.00,1.0,0.0,0.181818,0.25,0.666667,0.75,0.0,0.0,0.0
1130,1131,0.176471,0.75,0.418208,0.350779,1.0,1.0,0.000000,0.333333,1.0,...,0.50,1.0,0.0,1.000000,0.75,0.666667,0.75,0.0,0.0,0.0
1294,1295,0.000000,0.75,0.388581,0.359797,1.0,1.0,0.000000,0.333333,1.0,...,1.00,1.0,0.0,0.272727,0.00,0.666667,0.75,0.0,0.0,0.0
860,861,0.176471,0.75,0.356375,0.346673,1.0,1.0,0.000000,0.333333,1.0,...,0.75,1.0,0.0,0.454545,0.25,0.666667,0.75,0.0,0.0,0.0
1126,1127,0.588235,0.75,0.342664,0.203866,1.0,1.0,0.000000,0.333333,1.0,...,1.00,1.0,0.0,0.454545,0.75,0.666667,0.75,0.0,0.0,0.0

In [8]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [9]:
y_pred = model.predict(X_test)

In [10]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)

Mean Squared Error: 0.01655954805940551
R-squared: 0.9112628698344991

### Tried with SGDRegressor

In [11]:
sgdr = SGDRegressor(max_iter=1000)
sgdr.fit(X_train, y_train)
print(sgdr)
print(f"number of iterations completed: {sgdr.n_iter_}, number of weight updates: {sgdr.t_}")

SGDRegressor()
number of iterations completed: 78, number of weight updates: 91105.0

In [12]:
y_pred_sgd = sgdr.predict(X_test)

In [13]:
mse = mean_squared_error(y_test, y_pred_sgd)
r2 = r2_score(y_test, y_pred_sgd)

print("Mean Squared Error:", mse)
print("R-squared:", r2)

Mean Squared Error: 5.470315591978106e+28
R-squared: -2.9313608378099462e+29